apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SNAME}
spec:
  template:
    metadata:
      name: ${SNAME}-${GITHUB_RUN_NUMBER}-dev
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - name: 'app'
        image: 'app'
        env:
          - name: 'TARGET'
            value: 'Staging'
  traffic:
  - revisionName: ${SNAME}-${GITHUB_RUN_NUMBER}-dev
    tag: new-tag-dev
    percent: 90
    # This revision name (LATEST = PREVIOUS) needs to exist in the Cloud Run
  - revisionName: ${CLOUD_RUN_LATEST_REVISION_DEV}
    tag: previous-tag-dev
    percent: 10