apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: 'nextjs-deploy-prod'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - name: 'app'
        image: 'app'
        env:
          - name: 'TARGET'
            value: 'Prod'
  traffic:
  - tag: new-tag-prod
    percent: 90
  - revisionName: nextjs-deploy-prod-lmmqwmdh
    percent: 10