apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: 'nextjs-deploy-dev'
spec:
  template:
    metadata:
      name: ${SERVICE_NAME}-dev-${GITHUB_RUN_NUMBER}
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - name: 'app'
        image: 'app'
        env:
          - name: 'TARGET'
            value: 'Staging'
  traffic:
  - revisionName: ${SERVICE_NAME}-dev-${GITHUB_RUN_NUMBER}
    tag: new-tag-dev
    percent: 90
  - revisionName: ${CLOUD_RUN_LATEST_REVISION_DEV}
    tag: previous-tag-dev
    percent: 10