apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: 'nextjs-deploy-dev'
spec:
  template:
    metadata:
      name: 'nextjs-deploy-dev-${{ github.run_number }}'
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - name: 'app'
        image: 'app'
        env:
          - name: 'TARGET'
            value: 'Staging'