apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: 'nextjs-deploy-prod'
spec:
  template:
    metadata:
      name: 'nextjs-app-prod-revision-name'
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - name: 'app'
        image: 'app'
        env:
          - name: 'TARGET'
            value: 'Prod'