name: nextjs-cloud-deploy

on:
  push:
    branches:
      - master
      - main

env:
  PROJECT_ID: united-night-397809
  REGION: us-east1
  REPO_NAME: nextjs-cloud-deploy

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3    

      - id: 'auth'
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.CLOUD_DEPLOY_SERVICE_ACCOUNT }}"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ env.PROJECT_ID }}'
          
      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker

      - name: Build and tag the docker image
        run: |-
          echo "gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ env.GITHUB_SHA }}"
          docker build . --tag "gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ env.GITHUB_SHA }}"

      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push "gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ env.GITHUB_SHA }}"

      - name: 'Cloud Deploy: Delivery pipeline'
        run: |-
          gcloud deploy apply --file .github/actions/local-action/gc-cd.yaml --region=${{ env.REGION }} --project=${{ env.PROJECT_ID }}

      - name: 'Create release name'
        run: |-
          echo "RELEASE_NAME=testing-release-${GITHUB_SHA::7}-${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}
          
      - name: 'Create release in Cloud Deploy'
        id: 'releaes'
        uses: 'google-github-actions/create-cloud-deploy-release@v0'
        with:
          delivery_pipeline: github-action-cd-pipeline
          name: '${{ env.RELEASE_NAME }}'
          region: 'us-east1'
          description: '${{ env.GITHUB_COMMIT_MSG }}'
          skaffold_file: '.github/actions/local-action/skaffold.yaml'
          images: 'app=gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ env.GITHUB_SHA }}'

      - name: 'Report Cloud Deploy release'
        run: |-
          echo "Created release ${{ steps.release.outputs.name }} "
          echo "Release link ${{ steps.release.outputs.link }} "