name: nextjs-cloud-deploy

on:
  push:
    branches:
      - master
      - main

env:
  PROJECT_ID: ${{ secrets.CLOUD_DEPLOY_PROJECT_NAME }}
  REGION: us-east1
  REPO_NAME: nextjs-cloud-deploy

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3    

      - id: 'auth'
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.CLOUD_DEPLOY_SERVICE_ACCOUNT }}"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ env.PROJECT_ID }}'
          
      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker
          echo "$GITHUB_CONTEXT"

      - name: Build and tag the docker image
        run: |-
          docker build . --tag "gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ github.sha }}"

      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push "gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ github.sha }}"

      - name: 'Export Environmental Variables with envsubst'
        run: |-
          export PROJECT_ID="${{ env.PROJECT_ID }}"
          export GITHUB_RUN_NUMBER="${{ github.run_number }}"
          export CLOUD_RUN_LATEST_REVISION_DEV=$(gcloud run services describe nextjs-deploy-dev \
          --format="value(status.latestReadyRevisionName)" \
          --platform=managed \
          --region=${{ env.REGION }})
          export CLOUD_RUN_LATEST_REVISION_PROD=$(gcloud run services describe nextjs-deploy-prod \
          --format="value(status.latestReadyRevisionName)" \
          --platform=managed \
          --region=${{ env.REGION }})

          envsubst < .github/actions/local-action/gc-cd.template.yaml > .github/actions/local-action/gc-cd.yaml
          envsubst < .github/actions/local-action/nextjs-app-dev.template.yaml > .github/actions/local-action/nextjs-app-dev.yaml
          envsubst < .github/actions/local-action/nextjs-app-prod.template.yaml > .github/actions/local-action/nextjs-app-prod.yaml
          envsubst < .github/actions/local-action/skaffold.template.yaml > .github/actions/local-action/skaffold.yaml

      - name: 'Cloud Deploy: Delivery pipeline'
        run: |-
          gcloud deploy apply --file .github/actions/local-action/gc-cd.yaml --region=${{ env.REGION }} --project=${{ env.PROJECT_ID }}

      - name: 'Create release name'
        run: |-
          echo "RELEASE_NAME=testing-release-${GITHUB_SHA::7}-${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}
          
      - name: 'Create release in Cloud Deploy'
        id: 'releaes'
        uses: 'google-github-actions/create-cloud-deploy-release@v0'
        with:
          delivery_pipeline: github-action-cd-pipeline
          name: '${{ env.RELEASE_NAME }}'
          region: 'us-east1'
          description: '${{ env.GITHUB_COMMIT_MSG }}'
          skaffold_file: '.github/actions/local-action/skaffold.yaml'
          images: 'app=gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}:${{ github.sha }}'

      - name: 'Report Cloud Deploy release'
        run: |-
          echo "Created release ${{ steps.release.outputs.name }} "
          echo "Release link ${{ steps.release.outputs.link }} "